name: IndexLands
version: '${version}'
main: net.miourasaki.indexlands.IndexLands
api-version: '1.21'
load: STARTUP
author: Miourasaki
description: "这次，一定能行的吧！"


libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.10
